### ISSUE TITLE
Another exception was thrown: NoSuchMethodError: The method 'call' was called on null

### ISSUE THREAD

**Issue by lennykmacedo** [gabuldev/camera_camera#13]
When using a mode: CameraMode.normal, return this error but with mode: CameraMode.fullscreen works fine

**Comment by agreensh** [comment]
Same here, iOS 13.3 (haven't tried Android), camera_camera version 1.0.29.

**Comment by gabuldev** [comment]
I solved. upgrade version 1.0.30
