### ISSUE TITLE
Flash

### ISSUE THREAD

**Issue by malikdoksoz** [gabuldev/camera_camera#14]
Does this package support flash (torch) ?

**Comment by gabuldev** [comment]
No man. Are you have any ideia with implement this?

**Comment by malikdoksoz** [comment]
I think you can reference this library https://pub.dev/packages/firebase_ml_vision

**Comment by leszekkrol** [comment]
Any update in that case?

**Comment by nekomaruh** [comment]
Is there any way to get the flash working? 
https://pub.dev/packages/camera_flash
