### ISSUE TITLE
Add feature to control camera resolution

### ISSUE THREAD

**Issue by edocabhi** [gabuldev/camera_camera#15]
The flutter camera plugin that is used here has the option to control the camera resolution. Currently, the available options are as following:

*   /// 352x288 on iOS, 240p (320x240) on Android
  low,

*  /// 480p (640x480 on iOS, 720x480 on Android)
  medium,

*  /// 720p (1280x720)
  high,

*  /// 1080p (1920x1080)
  veryHigh,

*  /// 2160p (3840x2160)
  ultraHigh,

*  /// The highest resolution available.
  max,

This feature can be useful for many applications that will use this plugin.

**Comment by edocabhi** [comment]
I do not see the option to do the above-mentioned resolution selection and hence I will be working on the PR for this. Please post a comment and let me know if the feature is already present.

**Comment by gabuldev** [comment]
I will add this options
