### ISSUE TITLE
Pub Get issue

### ISSUE THREAD

**Issue by daniele777** [gabuldev/camera_camera#17]
Process finished with exit code 1

Because camera_camera >=1.0.27 depends on rxdart ^0.23.1 and csf.map.v1 depends on rxdart ^0.24.0, camera_camera >=1.0.27 is forbidden.

So, because csf.map.v1 depends on camera_camera ^1.0.31, version solving failed.
pub get failed (1; So, because csf.map.v1 depends on camera_camera ^1.0.31, version solving failed.)

i update my dependency so... rxdart from 0.23 to 0.24.0 and camera from 1.0.27 to 1.0.31
but seems don't update... i tried to invalidate cache and restart and flutter clean.. error again...

**Comment by gabuldev** [comment]
I will solve it

**Comment by daniele777** [comment]
ok ..i update rx dart and was ok ..but now i have new error i add 

<application
      
        <activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>
         <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        
    </application>


After i add   minSdkVersion 21 in build gradle ... but now i have this error...


AILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\Dani\OneDrive\Documents\csf2020\android\app\src\main\AndroidManifest.xml:14:9-17:71: AAPT: error: resource style/Theme.AppCompat.Light.NoActionBar (aka csf.map.v1:style/Theme.AppCompat.Light.NoActionBar) not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**BUILD FAILED in 4s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin camera...
Running Gradle task 'assembleAarRelease'...
√ Built build\app\outputs\repo.
Building plugin cloud_firestore...
Running Gradle task 'assembleAarRelease'...
Finished with error: The plugin cloud_firestore could not be built due to the issue above.**

**Comment by daniele777** [comment]
Solve !!! thxxx
