### ISSUE TITLE
Previous screen moves vertically when camera is closed

### ISSUE THREAD

**Issue by chitgoks** [gabuldev/camera_camera#19]
![Screenshot_20200420_130007](https://user-images.githubusercontent.com/3955470/79715695-fe6fbe80-8306-11ea-99e1-2bfa8c27ec71.jpg)

The culprit is SystemChrome.setEnabledSystemUIOverlays([]). so perhaps some way to override this and ignore somewhat?

So currently, the phone os' app bar gets hidden when the camera is shown from within the app. when the camera is closed by the user, the app goes back to the front of the screen.

however, since the phone os appbar was hidden and will not be shown, the app's height gets resized. which does not look good.

**Comment by gabuldev** [comment]
Removed this  SystemChrome.setEnabledSystemUIOverlays([]) new version 2.0.0
