### ISSUE TITLE
Another exception was thrown: NoSuchMethodError: The method 'call' was called on null.

### ISSUE THREAD

**Issue by JHC2019** [gabuldev/camera_camera#2]
When using Camera(Mode: **CameraMode.normal**) An error will occur.

(CameraMode.fullscreen is right)

**Another exception was thrown: NoSuchMethodError: The method 'call' was called on null.**

**Comment by gabuldev** [comment]
Solve it

**Comment by agreensh** [comment]
Still happening in version 1.0.29, iOS 13.3 (haven't tried Android), CameraMode.normal.

**Comment by gabuldev** [comment]
Hi man. Thanks for you reporting

Em qua, 29 de jan de 2020 às 11:38, agreensh <notifications@github.com>
escreveu:
