### ISSUE TITLE
Front camera does not work when rotate icon is tapped.

### ISSUE THREAD

**Issue by chitgoks** [gabuldev/camera_camera#20]
i am guessing the rotate icon on the right is to switch between front and back camera, right?

it does not work in my device, huawei mate 20 pro. it does not switch.

This is the output of my smartphone camera descriptions returned

```
CameraDescription(0, CameraLensDirection.back, 90)
CameraDescription(1, CameraLensDirection.front, 270)
CameraDescription(2, CameraLensDirection.back, 90)
CameraDescription(3, CameraLensDirection.back, 90)
CameraDescription(4, CameraLensDirection.back, 90)
```
Not sure what the problem is because if index 1 is used, it should be correct since it is the front camera but somehow, it does not switch.

it does work in the emulator (shows various colored thick pixels if switched to front cam).

```
CameraDescription(0, CameraLensDirection.back, 90)
CameraDescription(1, CameraLensDirection.front, 90)
```

In your code bloc_camera.dart

```
void changeCamera() {
    var list = cameras.value;
    if (list.length == 2) 
....
```

This should be changed to if (list.length > 1) since in my case, i have 5 cameras (4 back and 1 front) so it will never switch to front cam.

If I am not mistaken, there are already front cameras that are more than 1. So perhaps loop through  the camera description list and get the first instance found that is either front or back.

**Comment by gabuldev** [comment]
When I create plugin don’t exist phone with many back cameras hehe. Thanks you solution

**Comment by chitgoks** [comment]
not a problem. i like your lib. simple with a  clean design 

i figure if you plan to add a zoom or flash this would be really slick everyone will be using it ;)

**Comment by mubaroqiqbal** [comment]
> When I create plugin don’t exist phone with many back cameras hehe. Thanks you solution

is there new version coming out soon?

**Comment by chitgoks** [comment]
@gabuldev  hi gabriel, will you be able to push this? i posted the solution.
