### ISSUE TITLE
I cant see button to get foto..

### ISSUE THREAD

**Issue by daniele777** [gabuldev/camera_camera#23]
Hi guys i add code for camera i see all ..windows for photo camera all.. but not button of photo..to get photo from camera and save file... how? help!

i insert this code : 

         DialogButton(
            child : Icon(Icons.photo_camera,
                color: Colors.white),

            onPressed: () async {

              val = await showDialog(
                  context: context,
                  builder: (context) => Camera(
                    mode: CameraMode.normal,
                    orientationEnablePhoto: CameraOrientation.landscape,
                    imageMask: CameraFocus.square(
                      color: Colors.black.withOpacity(0.5),
                    ),

                  ));
                setState(() { });
            },

Result is ... attach screenshoot..  

![Screenshot_20200510-111625](https://user-images.githubusercontent.com/8341788/81495328-d6450100-92af-11ea-9163-a5fc6a27e78f.png)

**Comment by gabuldev** [comment]
Try change  orientationEnablePhoto: CameraOrientation.landscape, for portrait

**Comment by matheusperez** [comment]
I'm closing this issue, if your problem persists, reopen it: D
