### ISSUE TITLE
Cropping an image inside a mask

### ISSUE THREAD

**Issue by JHC2019** [gabuldev/camera_camera#3]
Is it possible to add a function like cropping an image inside a mask directly?

Thanks.

**Comment by gabulsavul** [comment]
I think about this. You have a idea with implement this?

**Comment by JHC2019** [comment]
I think you can use image (https://pub.dev/packages/image) for processing, just pay attention to File can not be overwritten, need path_provider help to read and write File, and clear the cache regularly?

**Comment by JHC2019** [comment]
Then, I also want to know about the use of imageMask, the size of the image I actually grab is still slightly different from the preview image.

**Comment by gabuldev** [comment]
If cropping image used the real size.

**Comment by UlanNurmatov** [comment]
@gabuldev Hi. Any update on this? Is it possible to add this feature?
