### ISSUE TITLE
resource style not found

### ISSUE THREAD

**Issue by joharputr** [gabuldev/camera_camera#34]
![image](https://user-images.githubusercontent.com/32647004/90785662-c87e2d80-e32c-11ea-8170-3a55a019ab0e.png)

**Comment by andiksetyawan** [comment]
just delete line android:theme="@style/Theme.AppCompat.Light.NoActionBar" .
or  you can add style on android/app/src/main/res/values/styles.xml. bcause style Theme.AppCompat.Light.NoActionBar is not found.
