### ISSUE TITLE
when I take picture in android 10 error throws Session 0: Exception while stopping repeating:

### ISSUE THREAD

**Issue by tonimelki** [gabuldev/camera_camera#38]
Session 0: Exception while stopping repeating:
E/CameraCaptureSession( 7218): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
E/CameraCaptureSession( 7218): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2231)
E/CameraCaptureSession( 7218): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1241)
E/CameraCaptureSession( 7218): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:578)
E/CameraCaptureSession( 7218): 	at io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:480)
E/CameraCaptureSession( 7218): 	at io.flutter.plugins.camera.Camera.close(Camera.java:486)
E/CameraCaptureSession( 7218): 	at io.flutter.plugins.camera.Camera$2.onError(Camera.java:187)
E/CameraCaptureSession( 7218): 	at android.hardware.camera2.impl.CameraDeviceImpl.notifyError(CameraDeviceImpl.java:1629)
E/CameraCaptureSession( 7218): 	at android.hardware.camera2.impl.CameraDeviceImpl.lambda$oDs27OTfKFfK18rUW2nQxxkPdV0(Unknown Source:0)
E/CameraCaptureSession( 7218): 	at android.hardware.camera2.impl.-$$Lambda$CameraDeviceImpl$oDs27OTfKFfK18rUW2nQxxkPdV0.accept(Unknown Source:8)

**Comment by gabuldev** [comment]
You can information about device?

**Comment by tonimelki** [comment]
actually all the devices I tried on (emulators and a real device) with android 10 like pixels 2 API 30

**Comment by gabuldev** [comment]
try new version beta 2.0.0-beta
