### ISSUE TITLE
O foco realmente é um foco?

### ISSUE THREAD

**Issue by ernonemacher** [gabuldev/camera_camera#42]
Estava dando uma testada aqui e não entendi direito uma coisa. O foco que pode ser colocado, retangular ou oval. Vai interferir no foco da camera em si? Ou ele serve mais pro usuario enquadrar um objeto ?

I was testing the focus funcionality and there is something I am curious about. The focus itself will change the real camera focus? Or this is just for the user to frame an object?

**Comment by gabuldev** [comment]
Server so para enquadrar. Mas na versão 2.0 que estou finalizando seria possível fazer dessa forma
