### ISSUE TITLE
Getting error in android 12

### ISSUE THREAD

**Issue by udaysingh2** [gabuldev/camera_camera#82]
android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
E/CameraCaptureSession(11409): 	at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2405)
E/CameraCaptureSession(11409): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1324)
E/CameraCaptureSession(11409): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:579)
E/CameraCaptureSession(11409): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/flutter (11409): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: CameraException(captureTimeout, Picture capture request timed out)
E/flutter (11409): #0      CameraController.takePicture
package:camera/src/camera_controller.dart:346
E/flutter (11409): <asynchronous suspension>
E/flutter (11409):
D/EGL_emulation(11409): app_time_stats: avg=2603.35ms min=9.02ms max=22912.86ms count=9

**Comment by kenguyenduc** [comment]
Same problem here

**Comment by gabuldev** [comment]
Try use the last version to camera_camera
