### ISSUE TITLE
Error on compile with flutter 2.10.0

### ISSUE THREAD

**Issue by ronaldojr1804** [gabuldev/camera_camera#85]
Esse é o erro que tenho ao compilar:

[C:\Users\junio\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\camera-0.8.1]()+7\android\src\main\java\io\flutter\plugins\camera\CameraUtils.java:138: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_HIGH);
                                 ^
[C:\Users\junio\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\camera-0.8.1]()+7\android\src\main\java\io\flutter\plugins\camera\CameraUtils.java:142: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_2160P);
                                 ^
[C:\Users\junio\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\camera-0.8.1]()+7\android\src\main\java\io\flutter\plugins\camera\CameraUtils.java:146: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_1080P);

                                 ^
[C:\Users\junio\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\camera-0.8.1]()+7\android\src\main\java\io\flutter\plugins\camera\CameraUtils.java:150: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_720P);
                                 ^

[C:\Users\junio\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\camera-0.8.1]()+7\android\src\main\java\io\flutter\plugins\camera\CameraUtils.java:154: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_480P);
                                 ^
[C:\Users\junio\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\camera-0.8.1]()+7\android\src\main\java\io\flutter\plugins\camera\CameraUtils.java:158: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated

          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_QVGA);
                                 ^
[C:\Users\junio\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\camera-0.8.1]()+7\android\src\main\java\io\flutter\plugins\camera\CameraUtils.java:162: warning: [deprecation] get(int,int) in CamcorderProfile has been deprecated
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_LOW);
                                 ^
[C:\Users\junio\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\camera-0.8.1]()+7\android\src\main\java\io\flutter\plugins\camera\media\MediaRecorderBuilder.java:15: warning: [deprecation] MediaRecorder() in MediaRecorder has been deprecated
      return new MediaRecorder();
             ^

1 error
15 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ': camera :compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by Juanitocancino** [comment]
I have the same issue, i seems that the Package camera is on version '0.8.1+7' and the newer version of flutter requires a newer version of the package (0.9.4+12) or at least that is what i think

**Comment by Dev11-ultroNeous** [comment]
D:\demo\android\app\src\debug\AndroidManifest.xml Error:
        uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [:camera] D:\demo\build\camera\intermediates\library_manifest\debug\AndroidManifest.xml as the library might be using APIs not available in 16
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 21,
                or use tools:overrideLibrary="io.flutter.plugins.camera" to force usage (may lead to runtime failures)
│   }                                                                                                        │
│ }                                                                                                          │
│                                                                                                            │
│                                                                                                            │
│ Note that your app won't be available to users running Android SDKs below 21.                              │
│ Alternatively, try to find a version of this plugin that supports these lower versions of the Android SDK. │└────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by Juanitocancino** [comment]
@PriyankPatel99 and @Dev11-ultroNeous
I would recommend to check your "build.gradle" and if you don't have plugins that use Android SDK 31 (This message shouldn't been prompt: `One or more plugins require a higher Android SDK version.`) You can set the  compileSdkVersion to 30 and the minSdkVersion to 21 and the project should be able to build

**Comment by vichuer** [comment]
I am facing the same problem. Any one found a solution for this?

**Comment by Juanitocancino** [comment]
@vichuer i made a work around with this https://pub.dev/packages/camerawesome, it's a bit more complicated, but it  won't cause the error.

**Comment by vichuer** [comment]
> @vichuer i made a work around with this https://pub.dev/packages/camerawesome, it's a bit more complicated, but it won't cause the error.

Thats great. I will try that @Juanitocancino

**Comment by herrmonkey** [comment]
> @vichuer i made a work around with this https://pub.dev/packages/camerawesome, it's a bit more complicated, but it won't cause the error.

how???

**Comment by nietsmmar** [comment]
I downgraded my flutter SDK but I still got the same errors.

`flutter --version` outputs this:
```
Flutter 2.8.1 • channel unknown • unknown source
Framework • revision 77d935af4d (4 months ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1
```

Does anyone know what I have to do so I do not have this error message?

**Comment by Juanitocancino** [comment]
> I downgraded my flutter SDK but I still got the same errors.
> 
> `flutter --version` outputs this:
> 
> ```
> Flutter 2.8.1 • channel unknown • unknown source
> Framework • revision 77d935af4d (4 months ago) • 2021-12-16 08:37:33 -0800
> Engine • revision 890a5fca2e
> Tools • Dart 2.15.1
> ```
> 
> Does anyone know what I have to do so I do not have this error message?

Did you change your minSdkVersion and compileSdkVersion?

You could use min 21 and compile 30 an see if works.

**Comment by Juanitocancino** [comment]
@nietsmmar i forgot to put the "@" to mention you in the comment.

**Comment by nietsmmar** [comment]
@Juanitocancino thanks! this worked :) I hope there will be a fix for this package soon.

**Comment by gabuldev** [comment]
Try to you use the last version camera_camera
