### ISSUE TITLE
Breaking change on Flutter 1.12.13+hotfix.5

### ISSUE THREAD

**Issue by jeaanlucas** [gabuldev/camera_camera#9]
On the newest Flutter version, one of your project's depencies is breaking the current build.
The change is: "Breaking change to support the fact that AppLifecycleState.suspended has changed to AppLifecycleState.detached."
The alteration is on native_device_orientation.

Can you fix that?

**Comment by gabuldev** [comment]
Closed, upgrade version 1.0.29
